FROM alpine:latest
MAINTAINER Dimitrios Giouroukis <dimitrios.giouroukis@gmail.com>

RUN echo -e "@edge http://nl.alpinelinux.org/alpine/edge/main\n@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

CMD ["sh"]
