version: '2'
services:
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        restart: always
        volumes:
            - config-transmission:/config
            - /home/digiou/Downloads:/downloads
        ports:
            - "9091:9091"
            - "51413:51413"
            - "51413:51413/udp"
        environment:
            - PGID=1000
            - PUID=1000
            - TZ=Europe/Athens
    emby:
        image: emby/embyserver
        container_name: emby
        restart: always
        volumes:
            - /home/digiou/Downloads/complete:/data
            - config-emby:/config
        ports:
            - "8096:8096"
        environment:
            - APP_UID=1000
            - APP_GID=1000
    sonarr:
        image linuxserver/sonarr
        container_name: sonarr
        restart: always
        volumes:
            - config-sonarr:/config
            - /home/digiou/Downloads:/data
            - /dev/rtc:/dev/rtc:ro
        ports:
            - "8989:8989"
        environment:
            - PUID=1000
            - PGID=1000
volumes:
    config-emby:
        driver: local
    config-transmission:
        driver: local
    config-sonarr:
        driver: local
